// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADPAB9lBs77yQZGHL9jCuIoj65Vo_I97g',
    appId: '1:1061520891897:web:5979b70c15f80a05c5e728',
    messagingSenderId: '1061520891897',
    projectId: 'docapp-31d7a',
    authDomain: 'docapp-31d7a.firebaseapp.com',
    storageBucket: 'docapp-31d7a.appspot.com',
    measurementId: 'G-SZL1ZNPLQJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpRtg0c7fC20kXY-ilyUPCqPF_FLqTqOs',
    appId: '1:1061520891897:android:fd2d33a1e24c49d7c5e728',
    messagingSenderId: '1061520891897',
    projectId: 'docapp-31d7a',
    storageBucket: 'docapp-31d7a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqAJppCN79kRVy8sQhuxXJPRiHYndHjnY',
    appId: '1:1061520891897:ios:af4225c8e1b75948c5e728',
    messagingSenderId: '1061520891897',
    projectId: 'docapp-31d7a',
    storageBucket: 'docapp-31d7a.appspot.com',
    iosBundleId: 'com.example.doctorApp1',
  );
}
